
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Language;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIFERENCIA = 15;
  public static final int Coma = 34;
  public static final int CONST = 32;
  public static final int POR = 10;
  public static final int CHAR = 5;
  public static final int C_ABRE = 40;
  public static final int REMOVE = 20;
  public static final int ENTERO = 26;
  public static final int XOR = 25;
  public static final int CAR = 29;
  public static final int DOUBLE = 3;
  public static final int CONTINUE = 52;
  public static final int INT = 2;
  public static final int Dos_Puntos = 35;
  public static final int LLAVE_C = 44;
  public static final int FOR = 50;
  public static final int LLAVE_A = 43;
  public static final int MATCH = 47;
  public static final int IDENTIFICADOR = 33;
  public static final int NOT = 22;
  public static final int AND = 23;
  public static final int APPEND = 58;
  public static final int IGUAL = 37;
  public static final int CAD = 30;
  public static final int P_Coma = 36;
  public static final int OR = 24;
  public static final int BOOL = 4;
  public static final int Punto = 59;
  public static final int UMENOS = 54;
  public static final int IF = 45;
  public static final int C_CIERRA = 41;
  public static final int P_CIERRA = 39;
  public static final int EOF = 0;
  public static final int BOOLEAN = 28;
  public static final int DECIMAL = 27;
  public static final int RETURN = 53;
  public static final int NEW = 57;
  public static final int error = 1;
  public static final int MODULO = 13;
  public static final int MENOS = 9;
  public static final int MENOR = 16;
  public static final int START = 21;
  public static final int BREAK = 55;
  public static final int VOID = 7;
  public static final int MAYOR = 18;
  public static final int POTENCIA = 12;
  public static final int ELSE = 46;
  public static final int WHILE = 49;
  public static final int LIST = 56;
  public static final int DEFAULT = 48;
  public static final int MAYOR_IGUAL = 19;
  public static final int P_ABRE = 38;
  public static final int COMPARACION = 14;
  public static final int STRING = 6;
  public static final int MENOR_IGUAL = 17;
  public static final int STRUCT = 60;
  public static final int DIVISION = 11;
  public static final int VAR = 31;
  public static final int DO = 51;
  public static final int PRINT = 42;
  public static final int MAS = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "DOUBLE",
  "BOOL",
  "CHAR",
  "STRING",
  "VOID",
  "MAS",
  "MENOS",
  "POR",
  "DIVISION",
  "POTENCIA",
  "MODULO",
  "COMPARACION",
  "DIFERENCIA",
  "MENOR",
  "MENOR_IGUAL",
  "MAYOR",
  "MAYOR_IGUAL",
  "REMOVE",
  "START",
  "NOT",
  "AND",
  "OR",
  "XOR",
  "ENTERO",
  "DECIMAL",
  "BOOLEAN",
  "CAR",
  "CAD",
  "VAR",
  "CONST",
  "IDENTIFICADOR",
  "Coma",
  "Dos_Puntos",
  "P_Coma",
  "IGUAL",
  "P_ABRE",
  "P_CIERRA",
  "C_ABRE",
  "C_CIERRA",
  "PRINT",
  "LLAVE_A",
  "LLAVE_C",
  "IF",
  "ELSE",
  "MATCH",
  "DEFAULT",
  "WHILE",
  "FOR",
  "DO",
  "CONTINUE",
  "RETURN",
  "UMENOS",
  "BREAK",
  "LIST",
  "NEW",
  "APPEND",
  "Punto",
  "STRUCT"
  };
}

